#!/usr/bin/env julia

# Build (or extend) a daily snapshot index for the General registry.
#
# The index maps a UTC date to the registry's state at the end of that day, so that a
# resolver asking for "the registry as of three days ago" can turn that into a concrete
# commit without walking any git history itself. Only completed UTC days are recorded,
# which keeps every entry immutable once written: a past day's last commit never changes.
#
# Usage:
#     julia generate_index.jl [--index PATH] [--repo PATH] [--first YYYY-MM-DD]
#
# `--repo` reuses an existing General clone instead of making a temporary one. History is
# fetched into it as needed, so pass a throwaway clone rather than one you care about.

using Dates
using TOML

const REGISTRY_UUID = "23338594-aafe-5451-b93e-139f81909106"
const REGISTRY_REPO = "https://github.com/JuliaRegistries/General.git"
const TARBALL_URL = "https://codeload.github.com/JuliaRegistries/General/tar.gz"
const DEFAULT_FIRST = Date(2026, 1, 1)

struct Snapshot
    commit::String
    tree::String
end

function parse_args(argv)
    opts = Dict{String, String}()
    i = firstindex(argv)
    while i <= lastindex(argv)
        arg = argv[i]
        startswith(arg, "--") || error("unexpected argument $(repr(arg))")
        i < lastindex(argv) || error("missing value for $arg")
        opts[arg[3:end]] = argv[i + 1]
        i += 2
    end
    return opts
end

# Existing entries are trusted and never recomputed: rewriting them would churn the
# committed file for no reason, and they cannot legitimately change.
function load_index(path)
    isfile(path) || return Dict{Date, Snapshot}()
    data = TOML.parsefile(path)
    snapshots = get(data, "snapshots", Dict{String, Any}())
    return Dict(
        Date(date) => Snapshot(entry["commit"]::String, entry["tree"]::String)
            for (date, entry) in snapshots
    )
end

function write_index(path, snapshots::Dict{Date, Snapshot})
    open(path, "w") do io
        println(io, "# Daily snapshots of the General registry.")
        println(io, "#")
        println(io, "# Each entry maps a UTC date to the last commit made on or before the end of that")
        println(io, "# day, along with that commit's git tree hash. Fetch a snapshot's registry with:")
        println(io, "#")
        println(io, "#     $TARBALL_URL/<commit>")
        println(io, "#")
        println(io, "# The unpacked tarball hashes to `tree`, so downloads can be verified offline.")
        println(io, "# Generated by generate_index.jl -- do not edit by hand.")
        println(io)
        println(io, "uuid = ", repr(REGISTRY_UUID))
        println(io, "repo = ", repr(REGISTRY_REPO))
        println(io, "tarball_url = ", repr(TARBALL_URL))
        println(io)
        println(io, "[snapshots]")
        for date in sort!(collect(keys(snapshots)))
            snap = snapshots[date]
            println(io, repr(string(date)), " = { commit = ", repr(snap.commit), ", tree = ", repr(snap.tree), " }")
        end
    end
    return path
end

# A clone deep enough to cover `since`, and the ref to read history from.
#
# Only commit metadata is ever read, so the clone is bare and blobless: checking out
# General's ~60k files costs minutes, while skipping them makes this a couple of seconds.
# `--shallow-since` then keeps even that proportional to the gap being filled, so a daily
# run fetches a day or two of commits rather than the whole registry.
function prepare_repo(repo_path, since::Date)
    since_str = string(since)
    if repo_path === nothing
        dir = mktempdir()
        run(`git clone --quiet --bare --single-branch --filter=blob:none --shallow-since=$since_str $REGISTRY_REPO $dir`)
        return dir, "HEAD"
    end
    run(`git -C $repo_path fetch --quiet --filter=blob:none --shallow-since=$since_str $REGISTRY_REPO master`)
    return repo_path, "FETCH_HEAD"
end

function read_history(repo::AbstractString, ref::AbstractString)
    out = read(`git -C $repo log --format=%ct%x09%H%x09%T $ref`, String)
    history = Tuple{DateTime, Snapshot}[]
    for line in eachsplit(strip(out), '\n')
        isempty(line) && continue
        stamp, commit, tree = split(line, '\t')
        push!(history, (unix2datetime(parse(Int, stamp)), Snapshot(commit, tree)))
    end
    # Committer timestamps are not strictly monotonic across the history, so sort rather
    # than relying on git's ordering before doing lookups by time.
    sort!(history; by = first)
    return history
end

function main(argv)
    opts = parse_args(argv)
    index_path = get(opts, "index", normpath(joinpath(@__DIR__, "..", "index.toml")))
    repo_path = get(opts, "repo", nothing)
    first_date = haskey(opts, "first") ? Date(opts["first"]) : DEFAULT_FIRST

    snapshots = load_index(index_path)
    # Today is still in progress, so the newest day that can be recorded is yesterday.
    last_date = Date(now(UTC)) - Day(1)
    start_date = isempty(snapshots) ? first_date : maximum(keys(snapshots)) + Day(1)

    if start_date > last_date
        println("index is up to date through $last_date ($(length(snapshots)) snapshots)")
        return 0
    end
    println("filling $start_date .. $last_date")

    # Fetch from a day before the gap so that a day with no commits of its own can still
    # resolve to the most recent earlier commit.
    repo, ref = prepare_repo(repo_path, start_date - Day(1))
    history = read_history(repo, ref)
    isempty(history) && error("no commits found in $repo")

    times = first.(history)
    added = 0
    for date in start_date:Day(1):last_date
        idx = searchsortedlast(times, DateTime(date + Day(1)) - Millisecond(1))
        # No commit at or before this day yet -- happens only before the registry existed.
        idx == 0 && continue
        snapshots[date] = history[idx][2]
        added += 1
    end

    write_index(index_path, snapshots)
    println("added $added snapshots; index now holds $(length(snapshots)) through $(maximum(keys(snapshots)))")
    return 0
end

if abspath(PROGRAM_FILE) == @__FILE__
    exit(main(ARGS))
end
